sudo: required
arch:
    - amd64
    - arm64
language: java
jdk:
- openjdk8
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
install: true
jobs:
  include:
  - stage: Compilation and Installation
    script: scripts/travis.sh install

