sudo: required
arch:
    - amd64
    - arm64
language: java
jdk:
- openjdk8
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
install: true
jobs:
  include:
  - stage: Compilation and Installation
    script: 
        - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
            sudo apt-get install -y maven openjdk-8-jdk;
          fi
        - scripts/travis.sh install
